from __future__ import annotations

import threading
from http.server import BaseHTTPRequestHandler, HTTPServer

from juicechain.core.info_gather import gather_info


class _Handler(BaseHTTPRequestHandler):
    # override default Server header behavior
    server_version = "nginx/1.18"
    sys_version = ""

    def do_GET(self):
        if self.path == "/" or self.path.startswith("/?"):
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("X-Powered-By", "Express")
            self.end_headers()
            self.wfile.write(b"<html><head><title>Juice Shop</title></head><body>ok</body></html>")
            return

        if self.path == "/robots.txt":
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; charset=utf-8")
            self.end_headers()
            self.wfile.write(
                b"User-agent: *\nDisallow: /admin\nDisallow: /secret\nSitemap: http://example.com/sitemap.xml\n"
            )
            return

        self.send_response(404)
        self.end_headers()

    def log_message(self, format, *args):
        return


def _run_server(server: HTTPServer):
    server.serve_forever(poll_interval=0.1)


def test_gather_info_home_and_robots():
    server = HTTPServer(("127.0.0.1", 0), _Handler)
    host, port = server.server_address

    t = threading.Thread(target=_run_server, args=(server,), daemon=True)
    t.start()

    try:
        res = gather_info(f"{host}:{port}", timeout=1.0, max_bytes=50_000)

        assert res["ok"] is True
        assert res["homepage"]["status_code"] == 200
        assert res["homepage"]["title"] == "Juice Shop"

        fp = res["fingerprint"]
        # Server header is generated by BaseHTTPRequestHandler from server_version/sys_version
        assert fp["server"] is not None
        assert fp["x_powered_by"] == "Express"
        assert "express" in fp["hints"]

        rob = res["robots"]
        assert rob["ok"] is True
        assert rob["status_code"] == 200
        assert "/admin" in rob["directives"]["disallow"]
        assert "/secret" in rob["directives"]["disallow"]
        assert "http://example.com/sitemap.xml" in rob["directives"]["sitemaps"]

    finally:
        server.shutdown()
        server.server_close()